# src/main/resources/application.properties
spring.datasource.url=jdbc:postgresql://localhost:1207/project
spring.datasource.username=postgres
spring.datasource.password=Quangtien12@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties
jwt.secret=Y1hsM1pYSjBlV2wwYkdsdVpYUnZaR1Z0YjNOMFpYSmxkbVZ5ZVd4dmJtYz0=
jwt.expiration=3600000

